openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /products:
    get:
      summary: Returns a list of products.
      description: If we receive the specified query parameters, the products are going to be filtered
      parameters:
        - name: stock
          in: query
          required: false
          description: If this query comes true, we are going to send only the products available
          schema:
            type: boolean
      responses:
        '200':
          description: A JSON array of product identifiers
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer