databaseChangeLog:
  - changeSet:
      id: 1
      author: Rodrigo Puerto
      changes:
        - createTable:
            tableName: product
            columns:
              - column:
                  name: id
                  type: bigint
                  constraints:
                    primaryKey: true
              - column:
                  name: sequence
                  type: int
                  constraints:
                    nullable: false


  - changeSet:
      id: 2
      author: Rodrigo Puerto
      changes:
        - createTable:
            tableName: size
            columns:
              - column:
                  name: id
                  type: bigint
                  constraints:
                    primaryKey: true
              - column:
                  name: back_soon
                  type: boolean
                  constraints:
                    nullable: false
              - column:
                  name: special
                  type: boolean
                  constraints:
                    nullable: false
              - column:
                  name: product_id
                  type: bigint
                  constraints:
                    nullable: true



  - changeSet:
      id: 3
      author: Rodrigo Puerto
      changes:
        - createTable:
            tableName: stock
            columns:
              - column:
                  name: size_id
                  type: bigint
                  constraints:
                    primaryKey: true
              - column:
                  name: quantity
                  type: int
                  defaultValueNumeric: 0
                  constraints:
                    nullable: false
                    min: 0


  - changeSet:
      id: 4
      author: Rodrigo Puerto
      changes:
        - loadData:
            file: classpath:data/product.csv
            tableName: product
            separator: ', '
            primaryKey: id
            columns:
              - column:
                  index: 0
                  name: id
                  type: NUMERIC
              - column:
                  index: 1
                  name: sequence
                  type: NUMERIC

  - changeSet:
      id: 5
      author: Rodrigo Puerto
      changes:
        - loadData:
            file: classpath:data/size-1.csv
            tableName: size
            separator: ', '
            columns:
              - column:
                  index: 0
                  name: id
                  type: NUMERIC
              - column:
                  index: 1
                  name: product_id
                  type: NUMERIC
              - column:
                  index: 2
                  name: back_soon
                  type: BOOLEAN
              - column:
                  index: 3
                  name: special
                  type: BOOLEAN

  - changeSet:
      id: 6
      author: Rodrigo Puerto
      changes:
        - loadData:
            file: classpath:data/stock.csv
            tableName: stock
            separator: ', '
            columns:
              - column:
                  index: 0
                  name: size_id
                  type: NUMERIC
              - column:
                  index: 1
                  name: quantity
                  type: NUMERIC

  - changeSet:
      id: 7
      author: Rodrigo Puerto
      changes:
        - addForeignKeyConstraint:
            baseTableName: size
            baseColumnNames: id
            referencedTableName: stock
            referencedColumnNames: size_id
            constraintName: fk_size_stock_id

  - changeSet:
      id: 8
      author: Rodrigo Puerto
      changes:
        - addForeignKeyConstraint:
            baseTableName: size
            baseColumnNames: product_id
            referencedTableName: product
            referencedColumnNames: id
            constraintName: fk_size_product_id