spring:
  jpa:
    show-sql: true
    properties:
      hibernate.show_sql: true
      use_sql_comments: true
      format_sql: true
  liquibase:
  change-log: infrastructure/adapter-repository-postgres/src/main/resources/db/changelog/db.changelog-master.yaml
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE